enum SocketEvent {
  startGameSession,
  startWaitingRoom,
  waitingRoomReady,
  fetchWaitingRooms,
  gameSessionCanceled,
  timeLimitWaitingRoomsUpdate,
  timeLimitWaitingRoomsUpdateFriends,
  classicWaitingRoomsUpdateFriends,
  cancelWaitingRoom,
  playerLeftWaitingRoom,
  acceptTimeLimitOpponents,
  waitingRoomEmpty,
  gameStart,
  waitingRoomStateUpdate,

  message,
  updatedChatsList,
  getJoinableChatsCallBack,
  getJoinedChatsCallBack,
  selectChat,
  getUserId,
  usersOfChat,
  quitChat,
  createChat,
  joinChat,
  refreshData,
  guessDifference,
  endGame,
  giveUp,
  classicWaitingRoomsUpdate,
  differenceFound,
  joinWaitingRoom,
  launchGameSession,
  launchGame,

// Observer events
  fetchObserverGameSessions,
  observerGameSessionsUpdate,
  startObservingGameSession,
  observerGameStart,
  fetchCurrentTime,
  setupStartTimer,
  verifyFriendships,
  observersSessionUpdate
}
